//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session5Api.Base
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Wells
    {
        public Wells()
        {
            this.WellLayers = new HashSet<WellLayers>();
        }
    
        public long ID { get; set; }
        public long WellTypeID { get; set; }
        public string WellName { get; set; }
        public long GasOilDepth { get; set; }
        public long Capacity { get; set; }
    

        [JsonIgnore]
        public virtual ICollection<WellLayers> WellLayers { get; set; }
        [JsonIgnore]
        public virtual WellTypes WellTypes { get; set; }
    }
}
