//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session5Api.Base
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class WellTypes
    {
        public WellTypes()
        {
            this.Wells = new HashSet<Wells>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<Wells> Wells { get; set; }
    }
}
