//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session5Api.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellLayers
    {
        public long ID { get; set; }
        public long WellID { get; set; }
        public long RockTypeID { get; set; }
        public long StartPoint { get; set; }
        public long EndPoint { get; set; }
    
        public virtual RockTypes RockTypes { get; set; }
        public virtual Wells Wells { get; set; }
    }
}
